import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigator from "@/components/Navigator";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex w-screen h-screen bg-blue-950`}>
        <Navigator></Navigator>
        <section className="flex flex-col w-full justify-between">
          <Header></Header>
          {children}
          <Footer></Footer>
        </section>
      </body>
    </html>
  );
}
